### ISSUE TITLE
Профайлер не работает

### ISSUE THREAD

**Issue by DelfikPro** [DelfikPro/Implario#17]
**Профайлер не работает**
При включении профайлера либо падает клиент, либо начинаются непереносимые фризы.

**Краш-репорт**
```
---- Отчёт об ошибке ----
// У тебя всё получится, я верю в тебя!

Время: 05.08.19 9:49
Описание: Exception ticking world

java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:422)
	at java.util.ArrayList.remove(ArrayList.java:499)
	at java.util.Collections$SynchronizedList.remove(Collections.java:2426)
	at net.minecraft.server.Profiler.endSection(Profiler.java:52)
	at net.minecraft.client.ClientProfiler.endSection(ClientProfiler.java:73)
	at net.minecraft.server.Profiler.endStartSection(Profiler.java:123)
	at net.minecraft.client.ClientProfiler.endStartSection(ClientProfiler.java:92)
	at net.minecraft.world.WorldServer.tick(WorldServer.java:187)
	at optifine.WorldServerOF.tick(WorldServerOF.java:23)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:603)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:545)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:156)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:452)
	at java.lang.Thread.run(Thread.java:748)


    ...
	Profiler Position: root.gameRenderer.level.updatechunks
```

**Comment by DelfikPro** [comment]
Исправлено в #18
