### ISSUE TITLE
Прелоадер конфликтует с FBO и быстрым рендером и клиент может упасть при загрузке

### ISSUE THREAD

**Issue by DelfikPro** [DelfikPro/Implario#20]
**Описание бага**
При включённой настройке `Использовать FBO` и выключенной `Быстрый рендер` существует вероятность того, что при начальной загрузке клиента рендер прелоадера начнёт конфликтовать с настройкой фреймбуфера. Игра может падать с самыми разными ошибками.

**Краш-репорт**
```
---- Отчёт об ошибке ----
// У тебя всё получится, я верю в тебя!

Время: 07.08.19 17:56
Описание: Initializing game

java.lang.IllegalStateException: Already building!
	at net.minecraft.client.renderer.WorldRenderer.begin(WorldRenderer.java:238)
	at net.minecraft.client.game.shader.Framebuffer.framebufferRenderExt(Framebuffer.java:213)
	at net.minecraft.client.game.shader.Framebuffer.framebufferRender(Framebuffer.java:181)
	at net.minecraft.client.gui.Preloader.drawLogo(Preloader.java:91)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:383)
	at net.minecraft.client.Minecraft.run(Minecraft.java:235)
	at net.minecraft.client.main.Main.main(Main.java:101)
	at Start.main(Start.java:12)


Детальная информация об ошибке (Покажите знакомому программисту):
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.WorldRenderer.begin(WorldRenderer.java:238)
	at net.minecraft.client.game.shader.Framebuffer.framebufferRenderExt(Framebuffer.java:213)
	at net.minecraft.client.game.shader.Framebuffer.framebufferRender(Framebuffer.java:181)
	at net.minecraft.client.gui.Preloader.drawLogo(Preloader.java:91)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:383)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.run(Minecraft.java:235)
	at net.minecraft.client.main.Main.main(Main.java:101)
	at Start.main(Start.java:12)

```

**Comment by DelfikPro** [comment]
Переход на новый прелоадер.
Коммит 820c69f62f1e1b09edb8aab35fcfaeaece770611
